# -*- coding: utf-8 -*-
"""app_starbucks.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAQRw0jc-26qSdWUCcsmZYUBACYeuL_1
"""

import streamlit as st
import joblib
import numpy as np

# Title
st.title("Starbucks MLR Prediction Model")

# Load model (default path)
model_path = "Starbucks_MLR.pkl"
model = joblib.load(model_path)

# Inputs
prepaid_amount = st.number_input("Amount on Prepaid Card", min_value=0.0, step=1.0)
age = st.number_input("Age", min_value=0, step=1)
days_per_month = st.number_input("Days per Month at Starbucks", min_value=0, step=1)
income = st.number_input("Income", min_value=0.0, step=100.0)

# Predict button
if st.button("Predict Cups of Coffee per Day"):
    # Prepare data
    input_data = np.array([[prepaid_amount, age, days_per_month, income]])

    # Predict
    prediction = model.predict(input_data)[0]

    # Display result
    st.write(f"**Predicted Cups of Coffee per Day:** {prediction:.2f}")